# Generated by Django 3.1.6 on 2026-07-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('insertion_order', '0001_initial'),
        ('company_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=120, unique=True, verbose_name='Invoice Number')),
                ('total_amount', models.FloatField(default=0.0)),
                ('due_date', models.DateField()),
                ('additional_discount', models.FloatField(default=0.0, verbose_name='Offers or Discount')),
                ('vat_tax', models.PositiveIntegerField(blank=True, default=0.0, null=True, verbose_name='VAT %')),
                ('gst', models.PositiveIntegerField(blank=True, null=True, verbose_name='GST %')),
                ('total_discount', models.FloatField(default=0.0, verbose_name='Bill Adjustment')),
                ('billing_amount', models.FloatField(default=0.0)),
                ('vat_tax_amount', models.FloatField(default=0.0)),
                ('gst_amount', models.FloatField(default=0.0)),
                ('invoice_on', models.DateField(verbose_name='Invoice Date')),
                ('invoice_from', models.DateField()),
                ('invoice_to', models.DateField()),
                ('is_approved', models.BooleanField(default=False, verbose_name='Manager Approved')),
                ('status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Partial Paid', 'Partial Paid'), ('Paid', 'Paid')], default='Not Paid', max_length=20, verbose_name='Payment Status')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Invoice Date')),
                ('updated_on', models.DateField(auto_now=True)),
                ('invoice_month', models.DateField(blank=True, null=True, verbose_name='Invoice Month')),
                ('invoice_type', models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', max_length=20)),
                ('authorized_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.invoiceauthorizedperson')),
                ('campaigns', models.ManyToManyField(related_name='invoiced_campaign', to='insertion_order.Campaigns')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companycontacts')),
                ('from_company_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.invoicecompanyaddress')),
                ('from_company_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.invoicebankdetails')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice',
                'db_table': 'tbl_invoice',
            },
        ),
        migrations.CreateModel(
            name='ServiceCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('amount', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoices')),
            ],
            options={
                'verbose_name': 'Services Charge',
                'verbose_name_plural': 'Services Charges',
                'db_table': 'tbl_invoice_services_charges',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(verbose_name='Transaction Date')),
                ('additional_info', models.CharField(blank=True, max_length=120, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='invoices.invoices')),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.modeofpayment')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment History',
                'db_table': 'tbl_payment_history',
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='OtherCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('amount', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_charges', to='invoices.invoices')),
            ],
            options={
                'verbose_name': 'Other Charge',
                'verbose_name_plural': 'Other Charges',
                'db_table': 'tbl_invoice_other_charges',
            },
        ),
        migrations.CreateModel(
            name='AllInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'All Invoice',
                'verbose_name_plural': 'All Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoices',),
        ),
        migrations.CreateModel(
            name='FullyPaid',
            fields=[
            ],
            options={
                'verbose_name': 'Fully Paid',
                'verbose_name_plural': 'Fully Paid Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoices',),
        ),
        migrations.CreateModel(
            name='NotPaid',
            fields=[
            ],
            options={
                'verbose_name': 'Not Paid',
                'verbose_name_plural': 'Not Paid Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoices',),
        ),
        migrations.CreateModel(
            name='NotPaidOverDue',
            fields=[
            ],
            options={
                'verbose_name': 'Not Paid and Overdue',
                'verbose_name_plural': 'Not Paid and Overdue Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoices',),
        ),
        migrations.CreateModel(
            name='PartiallyPaid',
            fields=[
            ],
            options={
                'verbose_name': 'Partially Paid',
                'verbose_name_plural': 'Partially Paid Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoices',),
        ),
        migrations.CreateModel(
            name='PartiallyPaidOverDue',
            fields=[
            ],
            options={
                'verbose_name': 'Partially Paid and OverDue',
                'verbose_name_plural': 'Partially Paid and OverDue Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoices',),
        ),
        migrations.CreateModel(
            name='BillingLineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('start_date', models.DateField(verbose_name='Billing Start Date')),
                ('end_date', models.DateField(verbose_name='Billing End Date')),
                ('unit_cost', models.FloatField()),
                ('volume', models.IntegerField()),
                ('net_cost', models.FloatField()),
                ('billing_cost', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('ad_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.metrics')),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.adsformats')),
                ('ethinicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.ethnicity')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoices')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion_order.iodetails')),
            ],
            options={
                'verbose_name_plural': 'Line Items',
                'db_table': 'tbl_invoice_line_item',
                'unique_together': {('invoice', 'line_item', 'description')},
            },
        ),
    ]
