# Generated by Django 3.1.6 on 2026-07-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insertion_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItemUnderPacing',
            fields=[
            ],
            options={
                'verbose_name': 'Under Pacing Line Item',
                'verbose_name_plural': 'Over Pacing Line Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insertion_order.iodetails',),
        ),
    ]
