# Generated by Django 3.1.6 on 2026-07-07 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insertion_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('body_of_content', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_campaign_request',
            },
        ),
        migrations.CreateModel(
            name='LineItemRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='Raise Status')),
                ('reason', models.CharField(max_length=256)),
                ('request_status', models.BooleanField(default=None, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion_order.iodetails', verbose_name='Line Item Name')),
            ],
            options={
                'verbose_name': 'Line Item Request',
                'verbose_name_plural': 'Line Item Request',
                'db_table': 'tbl_line_status_request',
            },
        ),
        migrations.CreateModel(
            name='CampaignRequestImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaign-request')),
                ('campaign_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientrequests.campaignrequest')),
            ],
            options={
                'db_table': 'tbl_campaign_request_images',
            },
        ),
    ]
