# Generated by Django 3.1.6 on 2026-07-07 12:16

import categories.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsFormats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Format',
                'verbose_name_plural': 'Ad Format',
                'db_table': 'tbl_ads_formats',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('dail_code', models.IntegerField()),
                ('iso_code_2', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Country Code')),
                ('iso_code_3', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Currency Code')),
                ('currency_symbols', models.CharField(max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to=categories.models.upload_to_title_images)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'tbl_country',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAuthorizedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('person_sign', models.ImageField(upload_to='authorized_person', verbose_name='Person Sign')),
                ('company_logo_sign', models.ImageField(upload_to='authorized_person_logo', verbose_name='Company Seal')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=100, unique=True)),
                ('swift_code', models.CharField(blank=True, max_length=100, null=True)),
                ('iban_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(max_length=100, unique=True)),
                ('bank_address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_invoice_bank_details',
            },
        ),
        migrations.CreateModel(
            name='InvoiceCompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=30, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=80, null=True)),
                ('cin_number', models.CharField(blank=True, max_length=80, null=True)),
                ('tan_number', models.CharField(blank=True, max_length=80, null=True)),
                ('trn_number', models.CharField(blank=True, max_length=80, null=True)),
                ('license_number', models.CharField(blank=True, max_length=80, null=True)),
                ('sac_number', models.CharField(blank=True, max_length=80, null=True)),
                ('ct_number', models.CharField(blank=True, max_length=80, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_invoice_company_details',
            },
        ),
        migrations.CreateModel(
            name='MediaTypeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Type Category',
                'verbose_name_plural': 'Media Type Categories',
                'db_table': 'tbl_media_type_category',
            },
        ),
        migrations.CreateModel(
            name='MediaTypeSuperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Type Super Category',
                'verbose_name_plural': 'Media Type Super Categories',
                'db_table': 'tbl_media_type_super_category',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metrics',
                'verbose_name_plural': 'Metrics',
                'db_table': 'tbl_metrics',
            },
        ),
        migrations.CreateModel(
            name='ModeOfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mode of Payment',
                'verbose_name_plural': 'Mode of Payment',
                'db_table': 'tbl_mode_of_payment',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Term',
                'verbose_name_plural': 'Payment Terms',
                'db_table': 'tbl_payment_terms',
            },
        ),
        migrations.CreateModel(
            name='PerformanceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_performance_category',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('company', models.CharField(choices=[('Billiontags', 'Billiontags'), ('Client', 'Client')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'tbl_teams_details',
                'unique_together': {('title', 'company')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='categories.performancecategory')),
            ],
            options={
                'db_table': 'tbl_item_performance',
            },
        ),
        migrations.CreateModel(
            name='MediaTypeSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.mediatypecategory')),
            ],
            options={
                'verbose_name': 'Media Type Sub Category',
                'verbose_name_plural': 'Media Type Sub Categories',
                'db_table': 'tbl_media_type_sub_category',
            },
        ),
        migrations.AddField(
            model_name='mediatypecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.mediatypesupercategory'),
        ),
        migrations.CreateModel(
            name='AedExchangeRateMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveSmallIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AED Exchange Rate Month',
                'verbose_name_plural': 'AED Exchange Rate Months',
                'db_table': 'tbl_aed_exchange_rate_month',
                'ordering': ('year', 'month'),
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.teams')),
            ],
            options={
                'verbose_name': 'Teams Role',
                'db_table': 'tbl_teams_role',
                'unique_together': {('team', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.country')),
            ],
            options={
                'verbose_name': 'Ethnicity',
                'verbose_name_plural': 'Ethnicity',
                'db_table': 'tbl_country_ethnicity',
                'unique_together': {('country', 'title')},
            },
        ),
        migrations.CreateModel(
            name='AedExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_date', models.DateField(help_text='CBUAE end-of-month date, eg: 2026-05-31')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='categories.currency')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='categories.aedexchangeratemonth')),
            ],
            options={
                'verbose_name': 'AED Exchange Rate',
                'verbose_name_plural': 'AED Exchange Rates',
                'db_table': 'tbl_aed_exchange_rate',
                'unique_together': {('month', 'currency')},
            },
        ),
    ]
