# Generated by Django 3.1.6 on 2026-07-07 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
        ('company_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Campaign ID')),
                ('report_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='Reporting ID')),
                ('name', models.CharField(max_length=120, verbose_name='Campaign Name')),
                ('work_order_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Client Campaign ID')),
                ('purchase_order_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Purchase Order ID')),
                ('start_date', models.DateField(verbose_name='Campaign Start Date')),
                ('end_date', models.DateField(verbose_name='Campaign End Date')),
                ('subagency', models.CharField(blank=True, max_length=120, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], max_length=20, verbose_name='Status')),
                ('payment_type', models.CharField(blank=True, choices=[('Pre Payment', 'Pre Payment'), ('Post Payment', 'Post Payment')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails', verbose_name='Client Name')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.paymentterms')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaign',
                'db_table': 'tbl_campaign',
            },
        ),
        migrations.CreateModel(
            name='InsertionOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=25, unique=True, verbose_name='IO ID')),
                ('report_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='Reporting ID')),
                ('name', models.CharField(max_length=120, verbose_name='IO Name')),
                ('work_order_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Client Campaign ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('geo', models.CharField(blank=True, max_length=256, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('Pre Payment', 'Pre Payment'), ('Post Payment', 'Post Payment')], max_length=50, null=True)),
                ('io_file', models.FileField(blank=True, null=True, upload_to='')),
                ('signed_io', models.FileField(blank=True, null=True, upload_to='', verbose_name='Signed IO')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], max_length=20, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='IO Date')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insertion_order', to='insertion_order.campaigns')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companycontacts')),
                ('order_taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.paymentterms')),
            ],
            options={
                'verbose_name': 'Insertion Order',
                'verbose_name_plural': 'Insertion Orders',
                'db_table': 'tbl_insertion_order',
            },
        ),
        migrations.CreateModel(
            name='IODetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=60, verbose_name='Line Item ID')),
                ('report_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='Reporting ID')),
                ('description', models.CharField(max_length=120, verbose_name='Line Item Name')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('unit_cost', models.FloatField()),
                ('volume', models.IntegerField()),
                ('avg_ctr', models.FloatField(verbose_name='Average CTR')),
                ('net_cost', models.FloatField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], max_length=20)),
                ('ad_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.metrics', verbose_name='Units')),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.adsformats', verbose_name='Ad Format')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.mediatypesubcategory')),
                ('ethinicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.ethnicity')),
                ('io', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_details', to='insertion_order.insertionorders')),
            ],
            options={
                'verbose_name': 'Booking Detail',
                'verbose_name_plural': 'Booking Details',
                'db_table': 'tbl_io_details',
                'ordering': ('id',),
                'unique_together': {('io', 'description')},
            },
        ),
        migrations.CreateModel(
            name='LineItemReportingID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=60, verbose_name='Reporting ID')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_ids', to='insertion_order.iodetails')),
            ],
            options={
                'verbose_name': 'Line Items Report',
                'verbose_name_plural': 'Line Items Report',
                'db_table': 'tbl_line_item_reports_id',
            },
        ),
        migrations.CreateModel(
            name='SubCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=20, unique=True, verbose_name='Sub Campaign ID')),
                ('report_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='Reporting ID')),
                ('name', models.CharField(max_length=120, verbose_name='Sub Campaign Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], max_length=20, verbose_name='Sub Campaign Status')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_campaign', to='insertion_order.campaigns', verbose_name='Campaign Name')),
            ],
            options={
                'verbose_name': 'Sub Campaign',
                'verbose_name_plural': 'Sub Campaigns',
                'db_table': 'tbl_sub_campaigns',
            },
        ),
        migrations.CreateModel(
            name='ReportingIdReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_on', models.DateField()),
                ('impression', models.PositiveIntegerField()),
                ('clicks', models.PositiveIntegerField()),
                ('viewable_impression', models.PositiveIntegerField(default=0)),
                ('measurable_impression', models.PositiveIntegerField(default=0)),
                ('video_start', models.PositiveIntegerField(default=0)),
                ('video_end', models.PositiveIntegerField(default=0)),
                ('fist_quartile_view', models.PositiveIntegerField(default=0, verbose_name='1st Quartile Views')),
                ('second_quartile_view', models.PositiveIntegerField(default=0, verbose_name='Midpoint Views')),
                ('third_quartile_view', models.PositiveIntegerField(default=0, verbose_name='3rd Quartile Views')),
                ('budget', models.FloatField(default=0.0, verbose_name='Revenue (Adv Currency)')),
                ('media_cost', models.FloatField(default=0.0, verbose_name='Media Cost (Advertiser Currency)')),
                ('reporting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting', to='insertion_order.lineitemreportingid')),
            ],
            options={
                'verbose_name': 'ReportId Report',
                'verbose_name_plural': 'ReportId Reports',
                'db_table': 'tbl_line_items_report_id_reports',
                'ordering': ('report_on',),
            },
        ),
        migrations.CreateModel(
            name='LineItemsReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_on', models.DateField()),
                ('impression', models.PositiveIntegerField()),
                ('clicks', models.PositiveIntegerField()),
                ('viewable_impression', models.PositiveIntegerField(default=0)),
                ('measurable_impression', models.PositiveIntegerField(default=0)),
                ('video_start', models.PositiveIntegerField(default=0)),
                ('video_end', models.PositiveIntegerField(default=0)),
                ('fist_quartile_view', models.PositiveIntegerField(default=0, verbose_name='1st Quartile Views')),
                ('second_quartile_view', models.PositiveIntegerField(default=0, verbose_name='Midpoint Views')),
                ('third_quartile_view', models.PositiveIntegerField(default=0, verbose_name='3rd Quartile Views')),
                ('budget', models.FloatField(default=0.0, verbose_name='Revenue (Adv Currency)')),
                ('media_cost', models.FloatField(default=0.0, verbose_name='Media Cost (Advertiser Currency)')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='insertion_order.iodetails')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'tbl_line_items_reports',
                'ordering': ('report_on',),
            },
        ),
        migrations.CreateModel(
            name='LineItemsPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('base_value', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='categories.performancesubcategory')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_performance', to='insertion_order.iodetails')),
            ],
            options={
                'verbose_name': 'Line Item',
                'db_table': 'tbl_line_item_performance',
            },
        ),
        migrations.AddField(
            model_name='insertionorders',
            name='sub_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertion_order', to='insertion_order.subcampaign'),
        ),
        migrations.CreateModel(
            name='EmailCCContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_email', models.EmailField(max_length=254)),
                ('io', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion_order.insertionorders')),
            ],
            options={
                'verbose_name': 'CC Email',
                'verbose_name_plural': 'CC Emails',
                'db_table': 'tbl_io_cc_details',
            },
        ),
        migrations.CreateModel(
            name='ActiveCampaigns',
            fields=[
            ],
            options={
                'verbose_name': 'Live Campaign',
                'verbose_name_plural': '1. Live Campaigns',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insertion_order.campaigns',),
        ),
        migrations.CreateModel(
            name='CompletedCampaigns',
            fields=[
            ],
            options={
                'verbose_name': 'Completed Campaign',
                'verbose_name_plural': '3. Completed Campaigns',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insertion_order.campaigns',),
        ),
        migrations.CreateModel(
            name='InactiveCampaigns',
            fields=[
            ],
            options={
                'verbose_name': 'Upcoming Campaign',
                'verbose_name_plural': '2. Upcoming Campaigns',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insertion_order.campaigns',),
        ),
        migrations.CreateModel(
            name='LineItems',
            fields=[
            ],
            options={
                'verbose_name': 'Line Items',
                'verbose_name_plural': '4. Line Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insertion_order.iodetails',),
        ),
    ]
