"""
Django settings for billiontags_crm project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/

"""



import os
from pathlib import Path

# Install python dot env file 
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

PROJECT_ROOT = os.path.realpath(os.path.dirname(__file__))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

#SECRET_KEY = 'iafcf%twf1z6n!g+iz#ew2$y&#5nmz9r@k%l!05ddt+f52nuw='

SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = ['*']
#ALLOWED_HOSTS = ['*', 'crmtest.billiontags.com', 'www.crmtest.billiontags.com', '13.207.237.7']

# Application definition

INSTALLED_APPS = [
    # All are custom apps
    'categories.apps.CategoriesConfig',
    'company_details.apps.CompanyDetailsConfig',
    'insertion_order.apps.InsertionOrderConfig',
    'invoices.apps.InvoicesConfig',
    'clientrequests.apps.ClientrequestsConfig',
    'reports.apps.ReportsConfig',

    # Custom admin skin 
    'billiontags_crm.apps.SuitConfig',

    # Django built-ins 
    'django.contrib.humanize',   # number formatting (1000 → 1,000)
    'django.contrib.admin',      # admin panel
    'django.contrib.auth',       # authentication system
    'django.contrib.contenttypes',
    'django.contrib.sessions',   # session management
    'django.contrib.messages',   # flash message 
    'django.contrib.staticfiles',

    # Third party packages 
    'easy_pdf',                  # PDF generation
    'django_summernote',         # Rich text editor
    'widget_tweaks',             # Form field styling in templates
    'django_admin_listfilter_dropdown',     # Better admin filters
    'daterangefilter',           # Date range filter in admin
]

MIDDLEWARE = [ 
    'django.middleware.security.SecurityMiddleware',         #HTTPS, security headers
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'billiontags_crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'billiontags_crm.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        #'PASSWORD': "B'll'0nt@g$2k18",
        #'HOST': '65.0.33.94',
        #'HOST': '13.234.244.100',
        'HOST': os.getenv('DB_HOST'),
        'PORT':  os.getenv('DB_PORT'),
    },
}

# ---------------------------------------------------------------------------
# Email Configuration
# ---------------------------------------------------------------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Fail loudly if email sending breaks, instead of silently swallowing errors
EMAIL_FAIL_SILENTLY = False

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = False

USE_TZ = False
#USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (os.path.join(PROJECT_ROOT, 'static/'),)



MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')

MEDIA_URL = '/media/'

X_FRAME_OPTIONS = 'SAMEORIGIN'
SUMMERNOTE_THEME = 'bs4'

DATA_UPLOAD_MAX_MEMORY_SIZE = 20242880     # ~20MB

FILE_UPLOAD_MAX_MEMORY_SIZE = 20242880     # ~20MB

DATA_UPLOAD_MAX_NUMBER_FIELDS = 30000      # huge number!

# WKHTMLTOPDF_CMD = '/usr/bin/wkhtmltopdf'   # (linux)

# Activate 
# .\billiontags-crm-env\bin\activate.ps1     # linux           
# .\billiontags-crm-env\Scripts\Activate.ps1  # windows