# Generated by Django 3.1.6 on 2026-07-07 12:16

import company_details.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('digital_signature', models.ImageField(blank=True, null=True, upload_to='company-user-signature')),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('zipcode', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Contacts',
                'verbose_name_plural': 'Company Contacts',
                'db_table': 'tbl_company_contacts',
            },
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=60)),
                ('report_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='Reporting ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('zipcode', models.CharField(max_length=8)),
                ('gst_no', models.CharField(blank=True, max_length=40, null=True)),
                ('cin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('is_domestic', models.BooleanField()),
                ('enable_aed_invoice', models.BooleanField(default=False, help_text="If checked, an additional 'View AED Invoice' PDF option will be shown for this company's invoices.", verbose_name='Enable AED Invoice')),
                ('wallet_amount', models.PositiveIntegerField(default=0, verbose_name='Wallet Available Amount')),
                ('payment_type', models.CharField(choices=[('Pre Payment', 'Pre Payment'), ('Post Payment', 'Post Payment')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice_type', models.CharField(choices=[('single', 'Single Invoice'), ('multiple', 'Multiple Invoice')], default='single', max_length=20)),
                ('default_email_send_to', models.CharField(blank=True, max_length=500, null=True, validators=[company_details.models.validate_comma_separated_emails], verbose_name='Default Email To')),
                ('default_email_send_cc', models.CharField(blank=True, max_length=500, null=True, validators=[company_details.models.validate_comma_separated_emails], verbose_name='Default Email CC')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('billing_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_currency', to='categories.country')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_country', to='categories.country')),
                ('default_authorized_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.invoiceauthorizedperson', verbose_name='Authorized person')),
                ('default_contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_invoice_contact', to='company_details.companycontacts', verbose_name='Contact person')),
                ('default_invoice_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.invoicecompanyaddress', verbose_name='From company address')),
                ('default_invoice_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.invoicebankdetails', verbose_name='From bank account')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.paymentterms')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Details',
                'verbose_name_plural': 'Company Details',
                'db_table': 'tbl_company_details',
                'ordering': ['-client_id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyWalletHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('is_credit', models.BooleanField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_history', to='company_details.companydetails')),
            ],
            options={
                'verbose_name': 'Wallet History',
                'verbose_name_plural': 'Wallet History',
                'db_table': 'tbl_company_wallet_history',
            },
        ),
        migrations.AddField(
            model_name='companycontacts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails'),
        ),
        migrations.AddField(
            model_name='companycontacts',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.country'),
        ),
        migrations.AddField(
            model_name='companycontacts',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.roles', verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='companycontacts',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_contact_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('zipcode', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_details.companydetails')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.country')),
            ],
            options={
                'verbose_name': 'Company Address',
                'verbose_name_plural': 'Company Address',
                'db_table': 'tbl_company_address',
            },
        ),
    ]
