# Generated by Django 3.1.6 on 2026-07-06 12:50

import company_details.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0018_companydetails_enable_aed_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='default_email_send_cc',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[company_details.models.validate_comma_separated_emails], verbose_name='Default Email CC'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='default_email_send_to',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[company_details.models.validate_comma_separated_emails], verbose_name='Default Email To'),
        ),
    ]
